# Generated by Django 2.2.2 on 2019-06-21 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nama Campaign', max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi Campaign')),
                ('is_archived', models.BooleanField(default=False, help_text='Centang untuk Menyembunyikan Campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Foto Campaign', upload_to='campaign_photo')),
                ('campaign', models.ManyToManyField(help_text='Nama Campaign', related_name='photos_in_campaign', to='campaign.Campaign')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
