# Generated by Django 2.2.2 on 2019-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto Campaign', upload_to='campaign_photo'),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto Campaign', upload_to='campaign_data_photo'),
        ),
    ]
