# Generated by Django 2.2.2 on 2019-06-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20190621_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndata',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='campaign',
            field=models.ForeignKey(help_text='Nama Campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_in_campaign', to='campaign.Campaign'),
        ),
    ]
