# Generated by Django 2.2.2 on 2019-06-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20190621_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='license_no',
            field=models.CharField(db_index=True, default='', help_text='No Plat Driver', max_length=100),
        ),
    ]
