# Generated by Django 2.2.2 on 2019-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaigndata_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndata',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Centang untuk Menampilkan Data'),
        ),
    ]
